### ISSUE TITLE
I can't insert text on Minecraft

### ISSUE THREAD

**Issue by PUBGMOBILEgdpb** [longjunyu2/MCinaBox#283]
I can't write anything on Minecraft
Can't write server IP & writing on signs

**Comment by AyHa1810** [comment]
If you don't know how to open the keyboard, then you can tap on the <> icon while Minecraft is open. Then a box will appear. You need to tap on it to open the keyboard. If it's not working, then you can use [Hacker's keyboard](https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard) to type.

First, you need to install it.
Then, enable the keyboard by opening the app and then tapping on the 'enable keyboard' option.
Then, select the input method to hacker's keyboard by tapping on the 'set input method' option.

At this point, you can use the keyboard normally. But you can't use it in Minecraft yet. So follow this:
Open settings in the hacker's keyboard.
Then, scroll down and go to 'input mode settings' section.
Then, select the tick box in the 'use permanent notification' option. A permanent notification of hacker's keyboard will appear in the notification bar.
Now, you can use that notification to open the keyboard at any time, even in the Minecraft.


Sorry I don't meant to write this tutorial, since some of the people hates it. I just wanted to help. Btw I hope if it helped you.

**Comment by AyHa1810** [comment]
Still if it doesn't work, there could be a problem with MCinaBox in your phone.

**Comment by PUBGMOBILEgdpb** [comment]
> Still if it doesn't work, there could be a problem with MCinaBox in your phone.

Thank you! It works now
