### ISSUE TITLE
License no work

### ISSUE THREAD

**Issue by GruffLimon** [longjunyu2/MCinaBox#378]
![Screenshot_20200911-180624](https://user-images.githubusercontent.com/71141155/92942547-4af49b80-f45a-11ea-8d4e-47297f844ee2.jpg)
Please help

**Comment by MegaBlade** [comment]
install Java runtime, then create a username, I recommend using an offline
username so that the process is fast, install the Minecraft version 1.7.10
You have to install 100%, then go to all versions, global settings then
change the max memery, according to your cellphone ram, just leave one ram
or don't need to change it, for ram two change to 445, then for ram Three,
change it to 556, for four ram just 750, then after that play the
minecraft, after that I have an additional bonus, to install the mod, you
need the forge version, how to install it Follow the steps below, download
forge on google, look for forge 1.7.10 then click on the top, then download
universal, after downloading, enter the file that was downloaded earlier Go
to /android/data/com.aof.mcinabox/files/McinaBox/forge installer / paste,
then enter the McinaBox application, click on launcher settings, install
the forge, make sure the source is bmclapi,After finishing playing, oh yeah
for those who can't play because they don't have a keyboard, you can
download a lot on YouTube, just search for "McinaBox Keyboard"

Pada tanggal Sab, 12 Sep 2020 00.34, GruffLimon <notifications@github.com>
menulis:

**Comment by GruffLimon** [comment]
> ![Screenshot_20200911-180624](https://user-images.githubusercontent.com/71141155/92942547-4af49b80-f45a-11ea-8d4e-47297f844ee2.jpg)
> Please help
