### ISSUE TITLE
performance improvement needed

### ISSUE THREAD

**Issue by LegacyGamerHD** [longjunyu2/MCinaBox#59]
some performance is bad in 1.8 and higher is there a way also am using a s9+ exynos variount

**Comment by 18296565196** [comment]
Is there any performance problem with version 1.8 or above on your Samsung S9?

**Comment by LegacyGamerHD** [comment]
yes there is lol

**Comment by 18296565196** [comment]
We will reply to you later. Thank you for your reply and support

**Comment by nightloli** [comment]
You can start a server on a pc in your local network and connect there if you use wi-fi or have white ip. It helps since you don't need to keep a dedicated server on your phone. I managed to play with 31 mods shown by forge (ofcourse in fact it's lower) on my phone. Minecraft 1.7.10

**Comment by LegacyGamerHD** [comment]
@nightloli  notting todo with with that

**Comment by ankhel12** [comment]
I have this issue where the first time I installed the app with OptiFine, Minecraft 1.8.9 and 600 mb on memory allocation i got 50-60 fps. I had to uninstall the app because of another unrelated issue, the second time I installed mcinabox with same configuration it was 1-6 fps. I'm playing on Moto g7 power

**Comment by LegacyGamerHD** [comment]
I close this because people seems to not understand my issue or to stupid use [pojavlauncher](https://github.com/PojavLauncherTeam/PojavLauncher) if you have Android 10 because this project is dead af
